# R - right
# L - left
# U - up
# D - down

# W - width
# H - height

# TEXTS
PARAG_R = 40

# PLOTS
MALT_R, MALT_D = 40, 150
LOG_R, LOG_D = 40, 176
LV_BOTH_R, LV_BOTH_D = 40, 280
LV_BOTH_W_DIV = 2
COMPLV_BOTH_R, COMPLV_BOTH_D = 30, 300
COMPLV_BOTH_W_DIV = 2

# Headers
COMPLV_HEADER_BOTH_DIV = 2
COMPLV_HEADER_BOTH_R = 240